version: "2"
services:
  graphite:
    build: ./config
    restart: always
    ports:
        - "8080:80"
        - "8125:8125/udp"
        - "8126:8126"
        - "2003:2003"
        - "2004:2004"
    volumes:
        - "./data/graphite:/opt/graphite/storage/whisper"
        - ./log/graphite:/opt/graphite/storage/log
        - ./log/supervisor:/var/log/supervisor
  grafana_db:
    image: busybox:latest
    volumes:
     - "./data/grafana:/var/lib/grafana"
  grafana:
    image: grafana/grafana:4.6.3
    restart: always
    ports:
     - "80:3000"
    environment:
     - GF_SECURITY_ADMIN_PASSWORD=root
    volumes_from:
     - grafana_db
    links:
     - graphite
